baseURL: https://sourcebots.github.io/website
languageCode: en-gb
title: Sourcebots

staticDir: "static/build"

buildDrafts: false
buildFuture: true
buildExpired: true

enableGitInfo: false
enableRobotsTXT: true

disableHugoGeneratorInject: true
enableEmoji: true
MetaDataFormat: yaml

pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true
pygmentsUseClasses: true

disableKinds:
  - taxonomy
  - taxonomyTerm
