baseURL: https://sourcebots.github.io/website
languageCode: en-gb
title: Sourcebots
theme: mainroad
paginate: 10000  # disable pagination

params:
    subtitle: insert tagline here
    description: Sourcebots Robotics
    readmore: true
    opengraph: true
    postSections: 
      - blog
    widgets:
        search: false
        recent_articles: true
        tags: true
        social_github: sourcebots

outputFormats:
  ical:
    name: "ics"
    mediaType: "text/calendar"


outputs:
  home:
    - "html"
    - "rss"
  section:
    - "html"
    - "ics"

menu:
  main:
    - name: Docs
      url: https://sourcebots.github.io/docs
enableRobotsTXT: true
disableHugoGeneratorInject: true
enableEmoji: true
pygmentsCodeFencesGuessSyntax: true
